import fs from 'node:fs';
const letter=JSON.parse(fs.readFileSync(new URL('./founder-letter.json',import.meta.url),'utf8'));
const esc=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const id=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const url='/guides/be-the-one-they-follow/';
const portrait=`<figure class="founder-portrait"><img src="/assets/craig-stratton-headshot.png" width="1122" height="1402" alt="Craig Stratton, founder of Prosper"><figcaption>Craig Stratton · AI-assisted portrait based on his photograph.</figcaption></figure>`;
const author=`<div class="founder-author"><span>By</span><strong>Craig Stratton</strong><span>Founder, Prosper</span><img src="/assets/prosper-wordmark-official-header.webp" width="200" height="84" alt="Prosper"></div>`;
export const founderLetterFeature=`<section class="founder-feature" aria-labelledby="founder-feature-title"><div class="founder-feature-copy"><p class="eyebrow">Featured · A letter from the founder</p><h2 id="founder-feature-title"><a href="${url}">Be the one<br>they follow.</a></h2><p>${esc(letter.deck)}</p><div class="founder-feature-byline"><strong>Craig Stratton</strong><span>October 4, 2026 · Founder letter</span></div><img class="founder-feature-logo" src="/assets/prosper-wordmark-official-header.webp" width="134" height="58" alt="Prosper"><a class="button" href="${url}">Read Craig’s letter <span aria-hidden="true">↗</span></a></div><a class="founder-feature-photo" href="${url}" aria-label="Read Be the one they follow, by Craig Stratton"><img src="/assets/craig-stratton-headshot.png" width="1122" height="1402" alt="Craig Stratton"></a></section>`;
export function founderLetterBody(article){
 const sections=letter.sections.map(section=>`<section class="letter-section"${section.heading?` aria-labelledby="${id(section.heading)}"`:''}>${section.heading?`<h2 id="${id(section.heading)}">${esc(section.heading)}</h2>`:''}${section.paragraphs.map(p=>`<p${p===letter.pullQuote?' class="letter-refrain"':''}>${esc(p)}</p>`).join('')}${letter.sourceReferences.some(g=>g.sectionHeading===section.heading)?`<div class="letter-citations">Sources: ${letter.sourceReferences.filter(g=>g.sectionHeading===section.heading).map(g=>`<a href="#letter-source-${g.id}">${esc(g.label)}</a>`).join(' · ')}</div>`:''}</section>`).join('');
 return `<main id="main" class="shell founder-letter"><div class="breadcrumbs"><a href="/">Home</a> / Founder letter</div><header class="founder-header"><div><p class="eyebrow">${esc(letter.kicker)}</p><h1>Be the one<br>they follow.</h1><p class="founder-deck">${esc(letter.deck)}</p>${author}<div class="meta"><time datetime="2026-10-04">October 4, 2026</time><span>${article.minutes} min read</span></div><div class="share-row"><button type="button" data-copy-url="https://news.prospershield.io${url}">Copy link</button><button type="button" data-share>Share</button><button type="button" data-print>Print / save PDF</button><span class="share-status" role="status" aria-live="polite"></span></div></div>${portrait}</header><div class="founder-reading"><aside class="founder-rail" aria-label="In this letter"><p class="eyebrow">In this letter</p>${letter.sections.filter(s=>s.heading).map(s=>`<a href="#${id(s.heading)}">${esc(s.heading.toLowerCase().replace(/^./,x=>x.toUpperCase()))}</a>`).join('')}<a href="#rep-opportunity">For Prosper sales representatives</a><a href="#article-sources">Sources & context</a><blockquote>“${esc(letter.secondaryPullQuote)}”</blockquote></aside><article class="prose founder-prose">${sections}<div class="founder-signoff"><p>— Craig Stratton<br><span>Founder, Prosper</span></p><img src="/assets/craig-stratton-signature.png" width="1536" height="1024" alt="Craig Stratton’s signature artwork"></div><aside class="rep-opportunity" id="rep-opportunity" aria-labelledby="rep-heading"><p class="eyebrow">For Prosper sales representatives</p><h2 id="rep-heading">Current commission opportunity</h2>${letter.sidebar.split('\n\n').map(p=>`<p>${esc(p)}</p>`).join('')}</aside><section class="founder-next"><p class="eyebrow">Your next step</p><h2>${esc(letter.ctaHeading)}</h2><a class="button" href="${esc(letter.ctaUrl)}">${esc(letter.ctaDisplay)} <span aria-hidden="true">↗</span></a></section><section class="article-sources" id="article-sources"><h2>Sources & context</h2><p>This is a personal founder letter and opinion, published by Prosper. Business milestones and commission terms are supplied by Craig Stratton; earnings vary and are not guaranteed. The sources below support the energy context. For additional company history, visit the <a href="/guides/prosper-opportunity-source-room/">Prosper Source Room</a>.</p>${letter.sourceReferences.map(g=>`<div class="letter-source-group" id="letter-source-${g.id}"><h3>${esc(g.label)}</h3><ul>${g.sources.map(s=>`<li><a href="${esc(s.url)}">${esc(s.title)}</a></li>`).join('')}</ul></div>`).join('')}</section><p><a href="/#library">Explore more from Prosper News ↗</a></p></article></div></main>`;
}
