const record = (id, title, publisher, url, type, date, note, group) => ({id, title, publisher, url, type, date, note, group, checked:'2026-09-22'});

export const opportunitySources = [
  record('prosper-announcement','Prosper joins the TAG growth story','TMX Newsfile','https://www.newsfilecorp.com/release/278281','Company announcement','2025-12-17','TAG announced the Prosper Energy acquisition as an expansion of its solar installation and sales capabilities. Read the original announcement and the later filing context below.','headlines'),
  record('prosper-nasdaq','The announcement on Nasdaq','Nasdaq / Newsfile','https://www.nasdaq.com/press-release/awareness-group-acquires-prosper-energy-expanding-epc-and-sales-capabilities','Syndicated company release','2025-12-17','Nasdaq carries TAG’s announcement about Prosper’s role in its national platform. This is the same issuer release, not a separate Nasdaq endorsement.','headlines'),
  record('prosper-yahoo','The announcement on Yahoo Finance','Yahoo Finance / Newsfile','https://finance.yahoo.com/news/awareness-group-acquires-prosper-energy-120000228.html','Syndicated company release','2025-12-17','A second financial-news destination for the original announcement. Syndication expands access; it does not independently verify the company’s claims.','headlines'),
  record('prosper-cook','Prosper in the energy deal review','Cook M&A Advisory Services','https://cookma.com/app/uploads/2026/01/PE-Deals-Energy-December-2025.pdf#page=2','Third-party M&A review','December 2025 review','Cook’s monthly energy report lists Prosper Energy and The Awareness Group in its December transaction table. Open page 2 of the PDF.','coverage'),
  record('prosper-seale','Included in the annual HVACR report','Seale & Associates','https://www.sealeassociates.com/hubfs/2025%20Annual%20HVACR%20Report.pdf?hsLang=en#page=13','Third-party M&A review','2025 annual review','Seale’s transaction review includes the December 17 Prosper Energy / TAG deal. A third-party deal listing, not an audit of Prosper’s operating results.','coverage'),
  record('prosper-origin','A place in the Q4 transaction landscape','Origin Merchant Partners','https://www.originmerchant.com/wp-content/uploads/2026/03/Origin-Q4-2025-MA-Review-on-HVACR.pdf','Third-party M&A review','Q4 2025 review','Origin’s HVACR review includes Prosper Energy and TAG among its selected fourth-quarter transactions. Look for Prosper in the transaction table.','coverage'),
  record('prosper-privsource','The renewable-energy deal record','PrivSource','https://www.privsource.com/acquisitions/deal/the-awareness-group-acquires-prosper-energy-B6SqRy','Third-party deal database','2025-12-17','A dedicated deal summary describes the combination of Prosper’s installation and sales capabilities with TAG’s platform. This is transaction coverage, not a customer review.','coverage'),
  record('craig-powur','Craig Stratton, featured by Powur','Powur / SEC-hosted campaign exhibit','https://www.sec.gov/Archives/edgar/data/1639406/000167025424001063/document_2.pdf','Issuer campaign material','2024 filing','Powur’s campaign material features Craig Stratton as Prosper Solar’s founder and an investor. This is historical issuer material hosted by the SEC, not SEC endorsement or verification of current holdings.','people'),
  record('prosper-q-three','Inside the Prosper opportunity','Prosper','https://q3.prospershield.io/','Prosper-published update','July 2026 snapshot','Prosper’s own presentation of its operating story. Pipeline is an operational snapshot, not recognized revenue, collected cash or a guarantee of future results.','people'),
  record('tag-cole','Cole Farmer appointed COO','TAG / TMX Newsfile','https://www.newsfilecorp.com/release/294804','Company announcement','2026-04-29','TAG announced Cole Farmer’s appointment to lead operations as it scales its renewable-energy platform. A leadership development reported by the company.','growth'),
  record('tag-isaac','Isaac Curiel appointed construction chief','TAG / TMX Newsfile','https://www.newsfilecorp.com/release/295937','Company announcement','2026-05-05','TAG announced Isaac Curiel as chief construction officer, with a focus on construction execution and deployment across its markets.','growth'),
  record('tag-sanjay','A new finance leader for TAG','TAG / TMX Newsfile','https://www.newsfilecorp.com/release/296619','Company announcement','2026-05-08','TAG announced Sanjay Swarup as chief financial officer and described his accounting, audit and financial-management experience.','growth'),
  record('tag-storage','Solar-plus-storage program expansion','TAG / TMX Newsfile','https://www.newsfilecorp.com/release/297077','Company announcement','2026-05-12','TAG announced a solar-plus-battery PPA launch across seven markets. Availability, underwriting and property eligibility require current confirmation; this is not a homeowner offer.','growth'),
  record('prosper-filing','Read the acquisition and accounting context','The Awareness Group / SEC EDGAR','https://www.sec.gov/Archives/edgar/data/1386044/000147793226004328/fhld_10q.htm','Official company filing','Quarter ended June 30, 2026','Note 4 describes conditional consolidation and preliminary acquisition accounting. The filing also discusses restatements, going-concern uncertainty and outstanding reviews. Read the full record before drawing financial conclusions.','records'),
  record('tag-newsroom','Follow the TAAG company newsroom','OTC Markets','https://www.otcmarkets.com/stock/TAAG/news','Company news directory','Live directory','The company’s news stream provides a place to check subsequent announcements. A listing is not a recommendation, performance guarantee or exchange endorsement.','records'),
];

const groups = [
  ['headlines','01','The announcement','The Prosper story in financial media. The three links below carry the same company announcement.'],
  ['coverage','02','Independent deal coverage','M&A publishers and transaction databases that recorded the Prosper / TAG story.'],
  ['people','03','People & perspective','Craig’s industry involvement and Prosper’s own operating update.'],
  ['growth','04','More momentum','Additional leadership and solar-plus-storage announcements from the wider TAG platform.'],
  ['records','05','The official record','Original documents and continuing updates, with the important context intact.'],
];
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const tile = s => `<a class="room-tile" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><div class="room-tile-top"><span class="room-type">${esc(s.type)}</span><span aria-hidden="true">↗</span></div><p class="room-publisher">${esc(s.publisher)}</p><h3>${esc(s.title)}</h3><p class="room-note">${esc(s.note)}</p><div class="room-tile-bottom"><span>${esc(s.date)}</span><span>Open source <span aria-hidden="true">↗</span><span class="room-sr-only"> in a new tab</span></span></div></a>`;

export const sourceRoomFeature = `<section class="room-feature" aria-labelledby="room-feature-title"><div><p class="eyebrow">The Prosper opportunity</p><h2 id="room-feature-title">Meet the source room.</h2><p>Company milestones, Craig’s industry story and independent deal coverage. The original sources, one click away.</p></div><a class="button" href="/guides/prosper-opportunity-source-room/">Open the Source Room <span aria-hidden="true">↗</span></a></section>`;

export function sourceRoomBody() {
  return `<main id="main" class="shell source-room"><div class="breadcrumbs"><a href="/">Prosper News</a> / Source Room</div><header class="room-hero"><p class="eyebrow">The Prosper opportunity</p><h1>Source room.</h1><p class="room-dek">The story. The momentum.<br><em>The sources behind it.</em></p><p class="room-intro">Prosper’s opportunity brings together solar experience, homeowner relationships and the ambition to grow alongside The Awareness Group. Start with TAG’s December 2025 announcement, explore the independent deal coverage, and meet the people behind the story.</p><div class="room-meta"><span>Curated by Prosper News</span><span>Reviewed September 22, 2026</span></div><nav class="room-jumps" aria-label="Source categories">${groups.map(([id,,title])=>`<a href="#${id}">${esc(title)} <span aria-hidden="true">↓</span></a>`).join('')}</nav></header><div class="room-intro-note"><strong>Every tile opens the original source.</strong> This is a curated collection of company milestones and industry coverage, not an independent investment review. Evidence types are labeled; announcements, deal listings and customer reviews are different things.</div>${groups.map(([id,num,title,description])=>`<section class="room-section" id="${id}" aria-labelledby="${id}-title"><div class="room-section-head"><span class="room-index">${num}</span><div><h2 id="${id}-title">${esc(title)}</h2><p>${esc(description)}</p></div></div><div class="room-grid">${opportunitySources.filter(s=>s.group===id).map(tile).join('')}</div></section>`).join('')}<aside class="room-context"><p class="eyebrow">A clear view of the story</p><h2>Good news. Real context.</h2><p>TAG’s December release describes an acquisition, while its later filing describes conditional consolidation and preliminary accounting. Those are different statements, and both originals are linked above. The filing also includes financial and review uncertainties.</p><p>We have not independently verified the release’s installation totals, rating claims or future performance. No independent customer-review rating is represented here. Nothing on this page is an offer of securities, a promise of returns or a guarantee of homeowner savings.</p><a href="/about/">Our publishing standards <span aria-hidden="true">↗</span></a></aside><div class="room-end"><a href="/downloads/prosper-opportunity-source-room.md">Download the reading list</a><button type="button" data-copy-url="https://news.prospershield.io/guides/prosper-opportunity-source-room/">Copy this page link</button><span class="share-status" role="status" aria-live="polite"></span></div></main>`;
}
